export default {
  signUpByEmail: '/authorization/registration',
  signInByEmail: '/authorization/login',
  signInByVk: '/authorization/login/socialite/vk',
  forgetPassword: '/authorization/send-link-for-change-password',
  purchasesAll: '/personal-area/purchases',
  purchase: (id) => '/personal-area/purchases/show-key-card/' + id,
  postPurchaseFeedback: '/seller/create-feedback',
  getProfile: '/personal-area/profile',
  changePassword: '/personal-area/security',
  postChangeAvatar: '/personal-area/profile/edit-avatar',
  getAppeals: (category) => '/personal-area/appeals/' + category,
  getQuestionMessages: (category, id) => '/personal-area/appeals/' + category + '/to/' + id,
  postCreateQuestion: (category) => '/personal-area/appeals/' + category + '/create',
  postCreateMessage: (id) => '/personal-area/appeals/general/create-message/' + id,
  getSliderNews: '/news/small',
  getCardNews: '/news/big',
  getNewsById: (id) => '/news/' + id,
  getMainPage: '/main-page ',
  postEditProfile: '/personal-area/profile/edit-info',
  getSearchItems: (query) => '/personal-area/sale/add-key/search-items?' + query,
  getSaleItem: (query) => '/personal-area/sale/add-key/get-item?' + query,
  getItem: (id) => '/to-item/' + id,
  getItemProposals: (itemId, keyId) => '/to-item/' + itemId + '/' + keyId + '/more-sellers',
  postKeysFile: '/personal-area/sale/add-key/process-file',
  postNewSale: '/personal-area/sale/add-key'
}
